language: node_js
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
node_js:
  - "12.18.2"

jobs:
  include:
    - stage: Test, Unit, Lint, Coverage
      script:
        - npm install
        # "error  Parsing error: Unexpected token" still an issue
        # - npm run lint
        - npm run test
        - npm run coverage

    - stage: Deploy, Firebase serverless architecture
      if: branch = master
      script:
        - echo "Building"
        - npm install
        - npm run build
        - echo "Deploying"
      install:
        - npm install -g firebase-tools
      after-success:
        - firebase deploy --token $FIREBASE_TOKEN
